-- ================================================================
--  SQL Server Seed Data - Clinica Trinidad
--  Carga datos iniciales de prueba
--  Contrasena para todos los usuarios: Trinidad2026
--  BCrypt hash: $2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e
-- ================================================================

-- ================================================================
--  ROLES
-- ================================================================
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'ADMINISTRADOR', 'Administrador del sistema', 1);
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'GERENTE',       'Gerencia / dashboards',     1);
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'MEDICO',        'Medico especialista',       1);
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'RECEPCIONISTA', 'Personal de admision',      1);
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'ENFERMERA',     'Personal de enfermeria',    1);
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_ROL, 'PACIENTE',      'Paciente del centro medico', 1);

-- ================================================================
--  PERMISOS GRANULARES
--  Cada permiso representa una accion CRUD sobre un recurso.
--  Se asignan a roles via ROL_PERMISO usando subconsultas por nombre.
-- ================================================================

-- CITAS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_CREATE',       'Crear citas medicas',          'CITAS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_READ',         'Ver citas medicas',            'CITAS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_UPDATE',       'Modificar citas medicas',      'CITAS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_DELETE',       'Eliminar citas medicas',       'CITAS', 'DELETE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_CANCELAR',     'Cancelar citas',               'CITAS', 'CANCELAR', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'CITAS_CONFIRMAR',    'Confirmar citas',              'CITAS', 'CONFIRMAR', 1);

-- PACIENTES
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PACIENTES_CREATE',   'Registrar pacientes',           'PACIENTES', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PACIENTES_READ',     'Ver pacientes',                 'PACIENTES', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PACIENTES_UPDATE',   'Modificar pacientes',           'PACIENTES', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PACIENTES_DELETE',   'Eliminar pacientes',            'PACIENTES', 'DELETE', 1);

-- MEDICOS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'MEDICOS_CREATE',     'Registrar medicos',             'MEDICOS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'MEDICOS_READ',       'Ver medicos',                   'MEDICOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'MEDICOS_UPDATE',     'Modificar medicos',             'MEDICOS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'MEDICOS_DELETE',     'Eliminar medicos',              'MEDICOS', 'DELETE', 1);

-- ESPECIALIDADES
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ESPECIALIDADES_CREATE',  'Crear especialidades',       'ESPECIALIDADES', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ESPECIALIDADES_READ',    'Ver especialidades',         'ESPECIALIDADES', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ESPECIALIDADES_UPDATE',  'Modificar especialidades',   'ESPECIALIDADES', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ESPECIALIDADES_DELETE',  'Eliminar especialidades',    'ESPECIALIDADES', 'DELETE', 1);

-- HORARIOS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HORARIOS_CREATE',    'Crear horarios medicos',        'HORARIOS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HORARIOS_READ',      'Ver horarios medicos',          'HORARIOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HORARIOS_UPDATE',    'Modificar horarios medicos',    'HORARIOS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HORARIOS_DELETE',    'Eliminar horarios medicos',     'HORARIOS', 'DELETE', 1);

-- HISTORIAS CLINICAS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HISTORIAS_READ',     'Ver historias clinicas',        'HISTORIAS_CLINICAS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'HISTORIAS_UPDATE',   'Modificar historias clinicas',  'HISTORIAS_CLINICAS', 'UPDATE', 1);

-- ATENCIONES
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ATENCIONES_CREATE',  'Registrar atenciones',          'ATENCIONES', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ATENCIONES_READ',    'Ver atenciones',                'ATENCIONES', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ATENCIONES_UPDATE',  'Modificar atenciones',          'ATENCIONES', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ATENCIONES_DELETE',  'Eliminar atenciones',           'ATENCIONES', 'DELETE', 1);

-- RECETAS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'RECETAS_CREATE',     'Emitir recetas',                'RECETAS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'RECETAS_READ',       'Ver recetas',                   'RECETAS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'RECETAS_UPDATE',     'Modificar recetas',             'RECETAS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'RECETAS_DELETE',     'Eliminar recetas',              'RECETAS', 'DELETE', 1);

-- ORDENES DE EXAMEN
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ORDENES_CREATE',     'Solicitar examenes',            'ORDENES_EXAMEN', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ORDENES_READ',       'Ver ordenes de examen',         'ORDENES_EXAMEN', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ORDENES_UPDATE',     'Modificar ordenes de examen',   'ORDENES_EXAMEN', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ORDENES_DELETE',     'Eliminar ordenes de examen',    'ORDENES_EXAMEN', 'DELETE', 1);

-- PAGOS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PAGOS_CREATE',       'Registrar pagos',               'PAGOS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PAGOS_READ',         'Ver pagos',                     'PAGOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PAGOS_UPDATE',       'Modificar pagos',               'PAGOS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PAGOS_DELETE',       'Anular pagos',                  'PAGOS', 'DELETE', 1);

-- USUARIOS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'USUARIOS_CREATE',    'Crear usuarios del sistema',    'USUARIOS', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'USUARIOS_READ',      'Ver usuarios del sistema',      'USUARIOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'USUARIOS_UPDATE',    'Modificar usuarios',            'USUARIOS', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'USUARIOS_DELETE',    'Eliminar usuarios',             'USUARIOS', 'DELETE', 1);

-- ROLES
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ROLES_CREATE',       'Crear roles',                   'ROLES', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ROLES_READ',         'Ver roles',                     'ROLES', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ROLES_UPDATE',       'Modificar roles',               'ROLES', 'UPDATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'ROLES_DELETE',       'Eliminar roles',                'ROLES', 'DELETE', 1);

-- PERMISOS
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PERMISOS_READ',      'Ver permisos del sistema',      'PERMISOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'PERMISOS_ASSIGN',    'Asignar permisos a roles',      'PERMISOS', 'ASSIGN', 1);

-- REPORTES / AUDITORIA
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'REPORTES_VIEW',      'Ver reportes y dashboards',     'REPORTES', 'VIEW',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'AUDITORIA_VIEW',     'Ver log de auditoria',          'AUDITORIA', 'VIEW',  1);

-- TRIAJE
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'TRIAJE_CREATE',      'Realizar triaje',               'TRIAJE', 'CREATE', 1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'TRIAJE_READ',        'Ver triajes',                   'TRIAJE', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'TRIAJE_UPDATE',      'Modificar triajes',             'TRIAJE', 'UPDATE', 1);

-- DIAGNOSTICOS CIE-10
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'DIAGNOSTICOS_READ',  'Ver diagnosticos CIE-10',       'DIAGNOSTICOS', 'READ',   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES (NEXT VALUE FOR SEQ_PERMISO, 'DIAGNOSTICOS_UPDATE','Modificar diagnosticos CIE-10',  'DIAGNOSTICOS', 'UPDATE', 1);

-- ================================================================
--  ASIGNACION DE PERMISOS A ROLES
-- ================================================================

-- ADMINISTRADOR: todos los permisos
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'ADMINISTRADOR';

-- GERENTE: lectura de todo + reportes
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'GERENTE'
  AND p.NOMBRE IN (
    'CITAS_READ', 'CITAS_CANCELAR',
    'PACIENTES_READ',
    'MEDICOS_READ',
    'ESPECIALIDADES_READ',
    'HORARIOS_READ',
    'HISTORIAS_READ',
    'ATENCIONES_READ',
    'RECETAS_READ',
    'ORDENES_READ',
    'PAGOS_READ',
    'USUARIOS_READ',
    'ROLES_READ',
    'PERMISOS_READ',
    'REPORTES_VIEW',
    'AUDITORIA_VIEW',
    'TRIAJE_READ',
    'DIAGNOSTICOS_READ'
  );

-- MEDICO: citas (propias), atenciones, recetas, ordenes, historias
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'MEDICO'
  AND p.NOMBRE IN (
    'CITAS_READ', 'CITAS_UPDATE', 'CITAS_CANCELAR', 'CITAS_CONFIRMAR',
    'PACIENTES_READ',
    'HISTORIAS_READ', 'HISTORIAS_UPDATE',
    'ATENCIONES_CREATE', 'ATENCIONES_READ', 'ATENCIONES_UPDATE',
    'RECETAS_CREATE', 'RECETAS_READ', 'RECETAS_UPDATE',
    'ORDENES_CREATE', 'ORDENES_READ', 'ORDENES_UPDATE',
    'TRIAJE_READ',
    'DIAGNOSTICOS_READ',
    'ESPECIALIDADES_READ',
    'HORARIOS_READ',
    'PERMISOS_READ'
  );

-- RECEPCIONISTA: pacientes y citas (CRUD), pagos
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'RECEPCIONISTA'
  AND p.NOMBRE IN (
    'CITAS_CREATE', 'CITAS_READ', 'CITAS_UPDATE', 'CITAS_CANCELAR', 'CITAS_CONFIRMAR',
    'PACIENTES_CREATE', 'PACIENTES_READ', 'PACIENTES_UPDATE',
    'PAGOS_CREATE', 'PAGOS_READ', 'PAGOS_UPDATE',
    'ESPECIALIDADES_READ',
    'MEDICOS_READ',
    'HORARIOS_READ',
    'TRIAJE_READ',
    'DIAGNOSTICOS_READ',
    'PERMISOS_READ'
  );

-- ENFERMERA: triaje, lectura de pacientes y citas
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'ENFERMERA'
  AND p.NOMBRE IN (
    'TRIAJE_CREATE', 'TRIAJE_READ', 'TRIAJE_UPDATE',
    'PACIENTES_READ',
    'CITAS_READ',
    'HISTORIAS_READ',
    'ESPECIALIDADES_READ',
    'MEDICOS_READ',
    'PERMISOS_READ'
  );

-- PACIENTE: solo datos propios
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'PACIENTE'
  AND p.NOMBRE IN (
    'CITAS_CREATE', 'CITAS_READ', 'CITAS_CANCELAR',
    'PACIENTES_READ',
    'ESPECIALIDADES_READ',
    'MEDICOS_READ',
    'HORARIOS_READ',
    'RECETAS_READ',
    'ORDENES_READ',
    'PAGOS_READ',
    'DIAGNOSTICOS_READ',
    'PERMISOS_READ'
  );

-- ================================================================
--  USUARIOS (password = Trinidad2026)
--  Todos usan el mismo hash BCrypt generado con rounds=10
-- ================================================================
INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'admin',     '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'admin@trinidadtarapoto.com',     1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'gerente',   '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'gerente@trinidadtarapoto.com',   1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'recepcion', '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'recepcion@trinidadtarapoto.com', 1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'enfermera', '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'enfermera@trinidadtarapoto.com', 1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'dr.garcia', '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'dr.garcia@trinidadtarapoto.com', 1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'dra.lopez', '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'dra.lopez@trinidadtarapoto.com', 1, 0, 0, SYSDATETIME());

INSERT INTO USUARIO (ID_USUARIO, USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES (NEXT VALUE FOR SEQ_USUARIO, 'paciente1', '$2b$10$/nqhBpL.6wu184xkEmaBuezMGsoTLVtbqSa9ZYSWZm643Srs6lf5e', 'paciente1@example.com',          1, 0, 0, SYSDATETIME());

-- ================================================================
--  ROLES POR USUARIO
-- ================================================================
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='admin'     AND r.NOMBRE='ADMINISTRADOR';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='gerente'   AND r.NOMBRE='GERENTE';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='recepcion' AND r.NOMBRE='RECEPCIONISTA';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='enfermera' AND r.NOMBRE='ENFERMERA';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dr.garcia' AND r.NOMBRE='MEDICO';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dra.lopez' AND r.NOMBRE='MEDICO';

INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='paciente1' AND r.NOMBRE='PACIENTE';

-- ================================================================
--  ESPECIALIDADES
-- ================================================================
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Medicina General',      50.00, 20, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Pediatria',             70.00, 20, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Ginecologia',           80.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Cardiologia',          100.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Traumatologia',         90.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Dermatologia',          85.00, 20, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Oftalmologia',          90.00, 20, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Otorrinolaringologia',  90.00, 20, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Neurologia',           110.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Psiquiatria',          120.00, 45, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Urologia',             100.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Endocrinologia',       100.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Gastroenterologia',    100.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Reumatologia',         110.00, 30, 1);
INSERT INTO ESPECIALIDAD (ID_ESPECIALIDAD, NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO)
VALUES (NEXT VALUE FOR SEQ_ESPECIALIDAD, 'Odontologia',           60.00, 30, 1);

-- ================================================================
--  DIAGNOSTICOS CIE-10
-- ================================================================
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('J00',   'Rinofaringitis aguda (resfriado comun)',                'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('J06.9', 'Infeccion aguda de las vias respiratorias superiores',  'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('K29.7', 'Gastritis no especificada',                             'Sistema digestivo',    1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('I10',   'Hipertension esencial (primaria)',                       'Sistema circulatorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones',          'Endocrinas',           1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('M54.5', 'Lumbago no especificado',                               'Sistema osteomuscular', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('R51',   'Cefalea',                                               'Sintomas generales',   1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('R50.9', 'Fiebre, no especificada',                               'Sintomas generales',   1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('Z00.0', 'Examen medico general de adulto',                       'Factores de salud',    1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO)
VALUES ('A09',   'Diarrea y gastroenteritis de presunto origen infeccioso', 'Infecciosas',         1);

-- ================================================================
--  MEDICOS
-- ================================================================
INSERT INTO MEDICO (ID_MEDICO, ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO, ACTIVO)
SELECT NEXT VALUE FOR SEQ_MEDICO, u.ID_USUARIO, e.ID_ESPECIALIDAD, '12345', 'Carlos', 'Garcia', 'Mendoza', '40123456', '942111222', 'dr.garcia@trinidadtarapoto.com', 'C-101', 1
FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dr.garcia' AND e.NOMBRE='Medicina General';

INSERT INTO MEDICO (ID_MEDICO, ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO, ACTIVO)
SELECT NEXT VALUE FOR SEQ_MEDICO, u.ID_USUARIO, e.ID_ESPECIALIDAD, '67890', 'Maria', 'Lopez', 'Vasquez', '40987654', '942333444', 'dra.lopez@trinidadtarapoto.com', 'C-205', 1
FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dra.lopez' AND e.NOMBRE='Pediatria';

-- ================================================================
--  HORARIOS (Lun-Vie)
-- ================================================================
-- Dr. Garcia: Lunes a Viernes 08:00-13:00
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 1, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 2, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 3, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 4, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 5, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';

-- Dra. Lopez: Lunes a Viernes 14:00-18:00
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 1, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 2, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 3, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 4, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_HORARIO, ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HORARIO_MEDICO, m.ID_MEDICO, 5, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='67890';

-- ================================================================
--  PACIENTES
-- ================================================================
INSERT INTO PACIENTE (ID_PACIENTE, ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, EMAIL, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
SELECT NEXT VALUE FOR SEQ_PACIENTE, u.ID_USUARIO, '70123456', 'Juan', 'Perez', 'Quispe', '1990-05-15', 'M', '942555666', 'paciente1@example.com', 'Jr. Lima 123', 'Tarapoto', 'O+', 1, SYSDATETIME()
FROM USUARIO u WHERE u.USERNAME='paciente1';

INSERT INTO PACIENTE (ID_PACIENTE, ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES (NEXT VALUE FOR SEQ_PACIENTE, NULL, '70234567', 'Ana',    'Rodriguez', 'Torres', '1985-08-22', 'F', '942777888', 'Av. Salaverry 456',  'Tarapoto', 'A+',  1, SYSDATETIME());

INSERT INTO PACIENTE (ID_PACIENTE, ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES (NEXT VALUE FOR SEQ_PACIENTE, NULL, '70345678', 'Luis',   'Sanchez',    'Vega',   '1978-12-03', 'M', '942999000', 'Calle Real 789',     'Morales',  'B+',  1, SYSDATETIME());

INSERT INTO PACIENTE (ID_PACIENTE, ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES (NEXT VALUE FOR SEQ_PACIENTE, NULL, '70456789', 'Carmen', 'Flores',     'Diaz',   '1995-03-18', 'F', '942111333', 'Jr. San Martin 234', 'Tarapoto', 'AB+', 1, SYSDATETIME());

-- ================================================================
--  HISTORIAS CLINICAS
-- ================================================================
INSERT INTO HISTORIA_CLINICA (ID_HISTORIA, ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HISTORIA_CLINICA, ID_PACIENTE, 'HC-2026-001', CAST(GETDATE() AS DATE), 1 FROM PACIENTE WHERE DNI='70123456';

INSERT INTO HISTORIA_CLINICA (ID_HISTORIA, ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HISTORIA_CLINICA, ID_PACIENTE, 'HC-2026-002', CAST(GETDATE() AS DATE), 1 FROM PACIENTE WHERE DNI='70234567';

INSERT INTO HISTORIA_CLINICA (ID_HISTORIA, ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HISTORIA_CLINICA, ID_PACIENTE, 'HC-2026-003', CAST(GETDATE() AS DATE), 1 FROM PACIENTE WHERE DNI='70345678';

INSERT INTO HISTORIA_CLINICA (ID_HISTORIA, ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT NEXT VALUE FOR SEQ_HISTORIA_CLINICA, ID_PACIENTE, 'HC-2026-004', CAST(GETDATE() AS DATE), 1 FROM PACIENTE WHERE DNI='70456789';

-- ================================================================
--  CITAS DE EJEMPLO
-- ================================================================
INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA, FECHA_REGISTRO)
SELECT NEXT VALUE FOR SEQ_CITA, p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, CAST(GETDATE() AS DATE),     '09:00', '09:20', 'PROGRAMADA', 'Control general',           'WEB', SYSDATETIME()
FROM PACIENTE p, MEDICO m WHERE p.DNI='70123456' AND m.CMP='12345';

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA, FECHA_REGISTRO)
SELECT NEXT VALUE FOR SEQ_CITA, p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, CAST(GETDATE() AS DATE),     '09:30', '09:50', 'CONFIRMADA', 'Dolor de cabeza recurrente', 'WEB', SYSDATETIME()
FROM PACIENTE p, MEDICO m WHERE p.DNI='70234567' AND m.CMP='12345';

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA, FECHA_REGISTRO)
SELECT NEXT VALUE FOR SEQ_CITA, p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, CAST(DATEADD(DAY, 1, GETDATE()) AS DATE), '14:00', '14:20', 'PROGRAMADA', 'Consulta pediatrica',        'WEB', SYSDATETIME()
FROM PACIENTE p, MEDICO m WHERE p.DNI='70456789' AND m.CMP='67890';

INSERT INTO CITA (ID_CITA, ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA, FECHA_REGISTRO)
SELECT NEXT VALUE FOR SEQ_CITA, p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, CAST(DATEADD(DAY, 2, GETDATE()) AS DATE), '10:00', '10:20', 'PROGRAMADA', 'Chequeo anual',              'PRESENCIAL', SYSDATETIME()
FROM PACIENTE p, MEDICO m WHERE p.DNI='70345678' AND m.CMP='12345';

-- ================================================================
--  VERIFICACION
-- ================================================================
SELECT 'PERMISO'          AS TABLA, COUNT(*) AS FILAS FROM PERMISO
UNION ALL SELECT 'ROL',              COUNT(*) FROM ROL
UNION ALL SELECT 'USUARIO',          COUNT(*) FROM USUARIO
UNION ALL SELECT 'ESPECIALIDAD',     COUNT(*) FROM ESPECIALIDAD
UNION ALL SELECT 'MEDICO',           COUNT(*) FROM MEDICO
UNION ALL SELECT 'PACIENTE',         COUNT(*) FROM PACIENTE
UNION ALL SELECT 'CITA',             COUNT(*) FROM CITA
UNION ALL SELECT 'DIAGNOSTICO_CIE10', COUNT(*) FROM DIAGNOSTICO_CIE10
UNION ALL SELECT 'PASSWORD_RESET_TOKEN', COUNT(*) FROM PASSWORD_RESET_TOKEN
ORDER BY TABLA;

PRINT 'Datos iniciales cargados correctamente';
GO
