-- =========================================================
-- TRINIDAD - Datos iniciales H2
-- Contraseña para todos los usuarios de prueba: Trinidad2026
-- BCrypt hash generado con rounds=10
-- =========================================================

-- ROLES
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('ADMINISTRADOR', 'Administrador del sistema', 1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('GERENTE',       'Gerencia y dashboards',     1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('MEDICO',        'Médico especialista',       1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('RECEPCIONISTA', 'Personal de admisión',      1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('PACIENTE',      'Paciente del centro',       1);

-- USUARIOS (password = Trinidad2026)
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('admin',     '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'admin@trinidad.com',     1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('gerente',   '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'gerente@trinidad.com',   1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('recepcion', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'recepcion@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('dr.garcia', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dr.garcia@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('paciente1', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'paciente1@gmail.com',    1, 0, 0, CURRENT_TIMESTAMP);

-- USUARIO_ROL
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='admin'     AND r.NOMBRE='ADMINISTRADOR';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='gerente'   AND r.NOMBRE='GERENTE';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='recepcion' AND r.NOMBRE='RECEPCIONISTA';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dr.garcia' AND r.NOMBRE='MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='paciente1' AND r.NOMBRE='PACIENTE';

-- ESPECIALIDADES
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Medicina General',  50.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Pediatria',         70.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Ginecologia',       80.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Cardiologia',      100.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Traumatologia',     90.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Dermatologia',      85.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Neurologia',       110.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Psiquiatria',      120.00, 45, 1);

-- CIE-10
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('J00',   'Rinofaringitis aguda (resfriado común)',                  'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('J06.9', 'Infección aguda de vías respiratorias superiores',        'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('K29.7', 'Gastritis no especificada',                               'Sistema digestivo',    1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('I10',   'Hipertensión esencial (primaria)',                         'Sistema circulatorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones',            'Endocrinas',           1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('M54.5', 'Lumbago no especificado',                                 'Osteomuscular',        1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('R51',   'Cefalea',                                                 'Síntomas generales',   1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('Z00.0', 'Examen médico general de adulto',                         'Salud',                1);

-- MEDICO (usa dr.garcia)
INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO, ACTIVO)
SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '12345', 'Carlos', 'Garcia', 'Mendoza', '40123456', '942111222', 'dr.garcia@trinidad.com', 'C-101', 1
FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dr.garcia' AND e.NOMBRE='Medicina General';

-- HORARIO del médico (lunes a viernes, 08:00-13:00)
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 1, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 2, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 3, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 4, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 5, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';

-- PACIENTES
INSERT INTO PACIENTE (ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, EMAIL, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
SELECT u.ID_USUARIO, '70123456', 'Juan', 'Perez', 'Quispe', '1990-05-15', 'M', '942555666', 'paciente1@gmail.com', 'Jr. Lima 123', 'Tarapoto', 'O+', 1, CURRENT_TIMESTAMP
FROM USUARIO u WHERE u.USERNAME='paciente1';

INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES ('70234567', 'Ana', 'Rodriguez', 'Torres', '1985-08-22', 'F', '942777888', 'Av. Salaverry 456', 'Tarapoto', 'A+', 1, CURRENT_TIMESTAMP);

INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES ('70345678', 'Luis', 'Sanchez', 'Vega', '1978-12-03', 'M', '942999000', 'Calle Real 789', 'Morales', 'B+', 1, CURRENT_TIMESTAMP);

-- HISTORIAS CLÍNICAS
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-001', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70123456';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-002', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70234567';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-003', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70345678';
