-- =========================================================
-- TRINIDAD - Datos iniciales H2
-- Contraseña para todos los usuarios de prueba: Trinidad2026
-- BCrypt hash generado con rounds=10
-- =========================================================

-- ================================================================
--  PERMISOS GRANULARES
--  ================================================================

-- CITAS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_CREATE',       'Crear citas medicas',          'CITAS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_READ',         'Ver citas medicas',            'CITAS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_UPDATE',       'Modificar citas medicas',      'CITAS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_DELETE',       'Eliminar citas medicas',       'CITAS', 'DELETE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_CANCELAR',     'Cancelar citas',               'CITAS', 'CANCELAR', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('CITAS_CONFIRMAR',    'Confirmar citas',              'CITAS', 'CONFIRMAR', 1);

-- PACIENTES
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PACIENTES_CREATE',   'Registrar pacientes',           'PACIENTES', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PACIENTES_READ',     'Ver pacientes',                 'PACIENTES', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PACIENTES_UPDATE',   'Modificar pacientes',           'PACIENTES', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PACIENTES_DELETE',   'Eliminar pacientes',            'PACIENTES', 'DELETE', 1);

-- MEDICOS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('MEDICOS_CREATE',     'Registrar medicos',             'MEDICOS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('MEDICOS_READ',       'Ver medicos',                   'MEDICOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('MEDICOS_UPDATE',     'Modificar medicos',             'MEDICOS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('MEDICOS_DELETE',     'Eliminar medicos',              'MEDICOS', 'DELETE', 1);

-- ESPECIALIDADES
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ESPECIALIDADES_CREATE',  'Crear especialidades',       'ESPECIALIDADES', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ESPECIALIDADES_READ',    'Ver especialidades',         'ESPECIALIDADES', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ESPECIALIDADES_UPDATE',  'Modificar especialidades',   'ESPECIALIDADES', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ESPECIALIDADES_DELETE',  'Eliminar especialidades',    'ESPECIALIDADES', 'DELETE', 1);

-- HORARIOS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HORARIOS_CREATE',    'Crear horarios medicos',        'HORARIOS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HORARIOS_READ',      'Ver horarios medicos',          'HORARIOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HORARIOS_UPDATE',    'Modificar horarios medicos',    'HORARIOS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HORARIOS_DELETE',    'Eliminar horarios medicos',     'HORARIOS', 'DELETE', 1);

-- HISTORIAS CLINICAS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HISTORIAS_READ',     'Ver historias clinicas',        'HISTORIAS_CLINICAS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('HISTORIAS_UPDATE',   'Modificar historias clinicas',  'HISTORIAS_CLINICAS', 'UPDATE', 1);

-- ATENCIONES
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ATENCIONES_CREATE',  'Registrar atenciones',          'ATENCIONES', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ATENCIONES_READ',    'Ver atenciones',                'ATENCIONES', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ATENCIONES_UPDATE',  'Modificar atenciones',          'ATENCIONES', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ATENCIONES_DELETE',  'Eliminar atenciones',           'ATENCIONES', 'DELETE', 1);

-- RECETAS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('RECETAS_CREATE',     'Emitir recetas',                'RECETAS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('RECETAS_READ',       'Ver recetas',                   'RECETAS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('RECETAS_UPDATE',     'Modificar recetas',             'RECETAS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('RECETAS_DELETE',     'Eliminar recetas',              'RECETAS', 'DELETE', 1);

-- ORDENES DE EXAMEN
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ORDENES_CREATE',     'Solicitar examenes',            'ORDENES_EXAMEN', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ORDENES_READ',       'Ver ordenes de examen',         'ORDENES_EXAMEN', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ORDENES_UPDATE',     'Modificar ordenes de examen',   'ORDENES_EXAMEN', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ORDENES_DELETE',     'Eliminar ordenes de examen',    'ORDENES_EXAMEN', 'DELETE', 1);

-- PAGOS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PAGOS_CREATE',       'Registrar pagos',               'PAGOS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PAGOS_READ',         'Ver pagos',                     'PAGOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PAGOS_UPDATE',       'Modificar pagos',               'PAGOS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PAGOS_DELETE',       'Anular pagos',                  'PAGOS', 'DELETE', 1);

-- USUARIOS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('USUARIOS_CREATE',    'Crear usuarios del sistema',    'USUARIOS', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('USUARIOS_READ',      'Ver usuarios del sistema',      'USUARIOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('USUARIOS_UPDATE',    'Modificar usuarios',            'USUARIOS', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('USUARIOS_DELETE',    'Eliminar usuarios',             'USUARIOS', 'DELETE', 1);

-- ROLES
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ROLES_CREATE',       'Crear roles',                   'ROLES', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ROLES_READ',         'Ver roles',                     'ROLES', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ROLES_UPDATE',       'Modificar roles',               'ROLES', 'UPDATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('ROLES_DELETE',       'Eliminar roles',                'ROLES', 'DELETE', 1);

-- PERMISOS
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PERMISOS_READ',      'Ver permisos del sistema',      'PERMISOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('PERMISOS_ASSIGN',    'Asignar permisos a roles',      'PERMISOS', 'ASSIGN', 1);

-- REPORTES / AUDITORIA
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('REPORTES_VIEW',      'Ver reportes y dashboards',     'REPORTES', 'VIEW',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('AUDITORIA_VIEW',     'Ver log de auditoria',          'AUDITORIA', 'VIEW',  1);

-- TRIAJE
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('TRIAJE_CREATE',      'Realizar triaje',               'TRIAJE', 'CREATE', 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('TRIAJE_READ',        'Ver triajes',                   'TRIAJE', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('TRIAJE_UPDATE',      'Modificar triajes',             'TRIAJE', 'UPDATE', 1);

-- DIAGNOSTICOS CIE-10
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('DIAGNOSTICOS_READ',  'Ver diagnosticos CIE-10',       'DIAGNOSTICOS', 'READ',   1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, RECURSO, ACCION, ACTIVO) VALUES ('DIAGNOSTICOS_UPDATE','Modificar diagnosticos CIE-10',  'DIAGNOSTICOS', 'UPDATE', 1);

-- ================================================================
--  ASIGNACION DE PERMISOS A ROLES
-- ================================================================

-- ADMINISTRADOR: todos los permisos
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO FROM ROL r, PERMISO p WHERE r.NOMBRE = 'ADMINISTRADOR';

-- GERENTE: lectura de todo + reportes
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'GERENTE'
  AND p.NOMBRE IN ('CITAS_READ','CITAS_CANCELAR','PACIENTES_READ','MEDICOS_READ',
                   'ESPECIALIDADES_READ','HORARIOS_READ','HISTORIAS_READ',
                   'ATENCIONES_READ','RECETAS_READ','ORDENES_READ','PAGOS_READ',
                   'USUARIOS_READ','ROLES_READ','PERMISOS_READ','REPORTES_VIEW',
                   'AUDITORIA_VIEW','TRIAJE_READ','DIAGNOSTICOS_READ');

-- MEDICO: citas propias, atenciones, recetas, ordenes, historias
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'MEDICO'
  AND p.NOMBRE IN ('CITAS_READ','CITAS_UPDATE','CITAS_CANCELAR','CITAS_CONFIRMAR',
                   'PACIENTES_READ','HISTORIAS_READ','HISTORIAS_UPDATE',
                   'ATENCIONES_CREATE','ATENCIONES_READ','ATENCIONES_UPDATE',
                   'RECETAS_CREATE','RECETAS_READ','RECETAS_UPDATE',
                   'ORDENES_CREATE','ORDENES_READ','ORDENES_UPDATE',
                   'TRIAJE_READ','DIAGNOSTICOS_READ',
                   'ESPECIALIDADES_READ','HORARIOS_READ','PERMISOS_READ');

-- RECEPCIONISTA: pacientes y citas (CRUD), pagos
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'RECEPCIONISTA'
  AND p.NOMBRE IN ('CITAS_CREATE','CITAS_READ','CITAS_UPDATE','CITAS_CANCELAR','CITAS_CONFIRMAR',
                   'PACIENTES_CREATE','PACIENTES_READ','PACIENTES_UPDATE',
                   'PAGOS_CREATE','PAGOS_READ','PAGOS_UPDATE',
                   'ESPECIALIDADES_READ','MEDICOS_READ','HORARIOS_READ',
                   'TRIAJE_READ','DIAGNOSTICOS_READ','PERMISOS_READ');

-- ENFERMERA: triaje, lectura de pacientes y citas
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'ENFERMERA'
  AND p.NOMBRE IN ('TRIAJE_CREATE','TRIAJE_READ','TRIAJE_UPDATE',
                   'PACIENTES_READ','CITAS_READ','HISTORIAS_READ',
                   'ESPECIALIDADES_READ','MEDICOS_READ','PERMISOS_READ');

-- PACIENTE: solo datos propios
INSERT INTO ROL_PERMISO (ID_ROL, ID_PERMISO)
SELECT r.ID_ROL, p.ID_PERMISO
FROM ROL r, PERMISO p
WHERE r.NOMBRE = 'PACIENTE'
  AND p.NOMBRE IN ('CITAS_CREATE','CITAS_READ','CITAS_CANCELAR',
                   'PACIENTES_READ','ESPECIALIDADES_READ','MEDICOS_READ',
                   'HORARIOS_READ','RECETAS_READ','ORDENES_READ','PAGOS_READ',
                   'DIAGNOSTICOS_READ','PERMISOS_READ');

-- ================================================================
--  ROLES
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('ADMINISTRADOR', 'Administrador del sistema', 1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('GERENTE',       'Gerencia y dashboards',     1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('MEDICO',        'Médico especialista',       1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('RECEPCIONISTA', 'Personal de admisión',      1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('ENFERMERA',     'Personal de enfermería',    1);
INSERT INTO ROL (NOMBRE, DESCRIPCION, ACTIVO) VALUES ('PACIENTE',      'Paciente del centro',       1);

-- USUARIOS (password = Trinidad2026)
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('admin',     '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'admin@trinidad.com',     1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('gerente',   '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'gerente@trinidad.com',   1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('recepcion', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'recepcion@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('dr.garcia', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dr.garcia@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('dra.lopez', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dra.lopez@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('enfermera', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'enfermera@trinidad.com', 1, 0, 0, CURRENT_TIMESTAMP);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
VALUES ('paciente1', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'paciente1@gmail.com',    1, 0, 0, CURRENT_TIMESTAMP);

-- USUARIO_ROL
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='admin'     AND r.NOMBRE='ADMINISTRADOR';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='gerente'   AND r.NOMBRE='GERENTE';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='recepcion' AND r.NOMBRE='RECEPCIONISTA';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dr.garcia' AND r.NOMBRE='MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dra.lopez' AND r.NOMBRE='MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='enfermera' AND r.NOMBRE='ENFERMERA';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL)
SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='paciente1' AND r.NOMBRE='PACIENTE';

-- ESPECIALIDADES
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Medicina General',  50.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Pediatria',         70.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Ginecologia',       80.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Cardiologia',      100.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Traumatologia',     90.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Dermatologia',      85.00, 20, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Neurologia',       110.00, 30, 1);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS, ACTIVO) VALUES ('Psiquiatria',      120.00, 45, 1);

-- CIE-10
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('J00',   'Rinofaringitis aguda (resfriado común)',                  'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('J06.9', 'Infección aguda de vías respiratorias superiores',        'Sistema respiratorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('K29.7', 'Gastritis no especificada',                               'Sistema digestivo',    1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('I10',   'Hipertensión esencial (primaria)',                         'Sistema circulatorio', 1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones',            'Endocrinas',           1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('M54.5', 'Lumbago no especificado',                                 'Osteomuscular',        1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('R51',   'Cefalea',                                                 'Síntomas generales',   1);
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO, ACTIVO) VALUES ('Z00.0', 'Examen médico general de adulto',                         'Salud',                1);

-- MEDICO (usa dr.garcia)
INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO, ACTIVO)
SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '12345', 'Carlos', 'Garcia', 'Mendoza', '40123456', '942111222', 'dr.garcia@trinidad.com', 'C-101', 1
FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dr.garcia' AND e.NOMBRE='Medicina General';

-- MEDICO (dra.lopez)
INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO, ACTIVO)
SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '54321', 'Maria', 'Lopez', 'Rios', '40123457', '942333444', 'dra.lopez@trinidad.com', 'C-102', 1
FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dra.lopez' AND e.NOMBRE='Pediatria';

-- HORARIO del médico dr.garcia (lunes a viernes, 08:00-13:00)
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 1, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 2, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 3, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 4, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 5, '08:00', '13:00', 1 FROM MEDICO m WHERE m.CMP='12345';

-- HORARIO de dra.lopez (lunes a viernes, 14:00-18:00)
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 1, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='54321';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 2, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='54321';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 3, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='54321';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 4, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='54321';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ACTIVO)
SELECT m.ID_MEDICO, 5, '14:00', '18:00', 1 FROM MEDICO m WHERE m.CMP='54321';

-- PACIENTES
INSERT INTO PACIENTE (ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, EMAIL, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
SELECT u.ID_USUARIO, '70123456', 'Juan', 'Perez', 'Quispe', '1990-05-15', 'M', '942555666', 'paciente1@gmail.com', 'Jr. Lima 123', 'Tarapoto', 'O+', 1, CURRENT_TIMESTAMP
FROM USUARIO u WHERE u.USERNAME='paciente1';

INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES ('70234567', 'Ana', 'Rodriguez', 'Torres', '1985-08-22', 'F', '942777888', 'Av. Salaverry 456', 'Tarapoto', 'A+', 1, CURRENT_TIMESTAMP);

INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE, ACTIVO, FECHA_REGISTRO)
VALUES ('70345678', 'Luis', 'Sanchez', 'Vega', '1978-12-03', 'M', '942999000', 'Calle Real 789', 'Morales', 'B+', 1, CURRENT_TIMESTAMP);

-- HISTORIAS CLÍNICAS
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-001', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70123456';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-002', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70234567';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA, FECHA_APERTURA, ACTIVO)
SELECT ID_PACIENTE, 'HC-2026-003', CURRENT_DATE, 1 FROM PACIENTE WHERE DNI='70345678';
