-- ================================================================
--  PASO 2 DE 2 - Ejecutar como TRINIDAD_DB en SQL Developer
--  Crea todas las tablas y carga los datos iniciales.
--  Se puede re-ejecutar para resetear la base de datos.
-- ================================================================
SET DEFINE OFF;

-- ================================================================
--  LIMPIEZA PREVIA (orden inverso de FK para evitar errores)
-- ================================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_LOG    CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAGO             CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDEN_EXAMEN     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_RECETA   CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECETA           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ATENCION         CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIAGNOSTICO_CIE10 CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITA             CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORIA_CLINICA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HORARIO_MEDICO   CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICO           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDAD     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACIENTE         CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO_ROL      CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROL              CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Secuencias
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ROL';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACIENTE';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ESPECIALIDAD';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICO';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HORARIO_MEDICO';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HISTORIA_CLINICA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CITA';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ATENCION';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECETA';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DETALLE_RECETA';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDEN_EXAMEN';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGO';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDITORIA_LOG';    EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ================================================================
--  CREACION DE TABLAS
-- ================================================================

-- 1) ROL
CREATE TABLE ROL (
    ID_ROL        NUMBER(10)        NOT NULL,
    NOMBRE        VARCHAR2(30 CHAR) NOT NULL,
    DESCRIPCION   VARCHAR2(200 CHAR),
    ACTIVO        NUMBER(1)         DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ROL        PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_ROL_ACTIVO CHECK (ACTIVO IN (0, 1))
);
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_ROL_BI BEFORE INSERT ON ROL FOR EACH ROW WHEN (NEW.ID_ROL IS NULL)
BEGIN :NEW.ID_ROL := SEQ_ROL.NEXTVAL; END;
/

-- 2) USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO        NUMBER(10)         NOT NULL,
    USERNAME          VARCHAR2(50 CHAR)  NOT NULL,
    PASSWORD_HASH     VARCHAR2(255 CHAR) NOT NULL,
    EMAIL             VARCHAR2(120 CHAR) NOT NULL,
    ACTIVO            NUMBER(1)          DEFAULT 1 NOT NULL,
    INTENTOS_FALLIDOS NUMBER(3)          DEFAULT 0 NOT NULL,
    BLOQUEADO         NUMBER(1)          DEFAULT 0 NOT NULL,
    FECHA_CREACION    TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ULT_LOGIN   TIMESTAMP,
    CONSTRAINT PK_USUARIO       PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_USER  UNIQUE (USERNAME),
    CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USUARIO_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT CK_USUARIO_BLOQ   CHECK (BLOQUEADO IN (0, 1))
);
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_USUARIO_BI BEFORE INSERT ON USUARIO FOR EACH ROW WHEN (NEW.ID_USUARIO IS NULL)
BEGIN :NEW.ID_USUARIO := SEQ_USUARIO.NEXTVAL; END;
/

-- 3) USUARIO_ROL
CREATE TABLE USUARIO_ROL (
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_ROL     NUMBER(10) NOT NULL,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USUARIO, ID_ROL),
    CONSTRAINT FK_UR_USUARIO  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROL      FOREIGN KEY (ID_ROL)     REFERENCES ROL (ID_ROL)
);

-- 4) PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE      NUMBER(10)        NOT NULL,
    ID_USUARIO       NUMBER(10),
    DNI              VARCHAR2(8 CHAR)  NOT NULL,
    NOMBRES          VARCHAR2(80 CHAR) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50 CHAR) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50 CHAR),
    FECHA_NACIMIENTO DATE              NOT NULL,
    SEXO             CHAR(1)           NOT NULL,
    TELEFONO         VARCHAR2(15 CHAR),
    EMAIL            VARCHAR2(120 CHAR),
    DIRECCION        VARCHAR2(200 CHAR),
    DISTRITO         VARCHAR2(80 CHAR),
    TIPO_SANGRE      VARCHAR2(5 CHAR),
    ALERGIAS         VARCHAR2(500 CHAR),
    ACTIVO           NUMBER(1)         DEFAULT 1 NOT NULL,
    FECHA_REGISTRO   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PACIENTE       PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT UQ_PACIENTE_DNI   UNIQUE (DNI),
    CONSTRAINT FK_PAC_USUARIO    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_PACIENTE_SEXO  CHECK (SEXO IN ('M', 'F')),
    CONSTRAINT CK_PACIENTE_DNI   CHECK (LENGTH(DNI) = 8 AND REGEXP_LIKE(DNI, '^[0-9]+$')),
    CONSTRAINT CK_PACIENTE_ACTIVO CHECK (ACTIVO IN (0, 1))
);
CREATE SEQUENCE SEQ_PACIENTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_PACIENTE_BI BEFORE INSERT ON PACIENTE FOR EACH ROW WHEN (NEW.ID_PACIENTE IS NULL)
BEGIN :NEW.ID_PACIENTE := SEQ_PACIENTE.NEXTVAL; END;
/

-- 5) ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    ID_ESPECIALIDAD  NUMBER(10)        NOT NULL,
    NOMBRE           VARCHAR2(80 CHAR) NOT NULL,
    DESCRIPCION      VARCHAR2(300 CHAR),
    PRECIO_CONSULTA  NUMBER(10, 2)     NOT NULL,
    DURACION_MINUTOS NUMBER(3)         DEFAULT 20 NOT NULL,
    ACTIVO           NUMBER(1)         DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD      PRIMARY KEY (ID_ESPECIALIDAD),
    CONSTRAINT UQ_ESPECIALIDAD_NOMB UNIQUE (NOMBRE),
    CONSTRAINT CK_ESPEC_PRECIO      CHECK (PRECIO_CONSULTA >= 0),
    CONSTRAINT CK_ESPEC_DURACION    CHECK (DURACION_MINUTOS BETWEEN 5 AND 240),
    CONSTRAINT CK_ESPEC_ACTIVO      CHECK (ACTIVO IN (0, 1))
);
CREATE SEQUENCE SEQ_ESPECIALIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_ESPECIALIDAD_BI BEFORE INSERT ON ESPECIALIDAD FOR EACH ROW WHEN (NEW.ID_ESPECIALIDAD IS NULL)
BEGIN :NEW.ID_ESPECIALIDAD := SEQ_ESPECIALIDAD.NEXTVAL; END;
/

-- 6) MEDICO
CREATE TABLE MEDICO (
    ID_MEDICO        NUMBER(10)        NOT NULL,
    ID_USUARIO       NUMBER(10)        NOT NULL,
    ID_ESPECIALIDAD  NUMBER(10)        NOT NULL,
    CMP              VARCHAR2(15 CHAR) NOT NULL,
    NOMBRES          VARCHAR2(80 CHAR) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50 CHAR) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50 CHAR),
    DNI              VARCHAR2(8 CHAR)  NOT NULL,
    TELEFONO         VARCHAR2(15 CHAR),
    EMAIL            VARCHAR2(120 CHAR),
    CONSULTORIO      VARCHAR2(20 CHAR),
    ACTIVO           NUMBER(1)         DEFAULT 1 NOT NULL,
    CONSTRAINT PK_MEDICO       PRIMARY KEY (ID_MEDICO),
    CONSTRAINT UQ_MEDICO_CMP   UNIQUE (CMP),
    CONSTRAINT UQ_MEDICO_DNI   UNIQUE (DNI),
    CONSTRAINT FK_MED_USUARIO  FOREIGN KEY (ID_USUARIO)      REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_MED_ESPEC    FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD),
    CONSTRAINT CK_MEDICO_DNI   CHECK (LENGTH(DNI) = 8 AND REGEXP_LIKE(DNI, '^[0-9]+$')),
    CONSTRAINT CK_MEDICO_ACTIVO CHECK (ACTIVO IN (0, 1))
);
CREATE SEQUENCE SEQ_MEDICO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_MEDICO_BI BEFORE INSERT ON MEDICO FOR EACH ROW WHEN (NEW.ID_MEDICO IS NULL)
BEGIN :NEW.ID_MEDICO := SEQ_MEDICO.NEXTVAL; END;
/

-- 7) HORARIO_MEDICO
CREATE TABLE HORARIO_MEDICO (
    ID_HORARIO  NUMBER(10)       NOT NULL,
    ID_MEDICO   NUMBER(10)       NOT NULL,
    DIA_SEMANA  NUMBER(1)        NOT NULL,
    HORA_INICIO VARCHAR2(5 CHAR) NOT NULL,
    HORA_FIN    VARCHAR2(5 CHAR) NOT NULL,
    ACTIVO      NUMBER(1)        DEFAULT 1 NOT NULL,
    CONSTRAINT PK_HORARIO_MEDICO PRIMARY KEY (ID_HORARIO),
    CONSTRAINT FK_HOR_MEDICO     FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO (ID_MEDICO) ON DELETE CASCADE,
    CONSTRAINT CK_HOR_DIA        CHECK (DIA_SEMANA BETWEEN 1 AND 7),
    CONSTRAINT CK_HOR_ACTIVO     CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UQ_HORARIO_UNICO  UNIQUE (ID_MEDICO, DIA_SEMANA, HORA_INICIO)
);
CREATE SEQUENCE SEQ_HORARIO_MEDICO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_HORARIO_MEDICO_BI BEFORE INSERT ON HORARIO_MEDICO FOR EACH ROW WHEN (NEW.ID_HORARIO IS NULL)
BEGIN :NEW.ID_HORARIO := SEQ_HORARIO_MEDICO.NEXTVAL; END;
/

-- 8) HISTORIA_CLINICA
CREATE TABLE HISTORIA_CLINICA (
    ID_HISTORIA    NUMBER(10)        NOT NULL,
    ID_PACIENTE    NUMBER(10)        NOT NULL,
    NRO_HISTORIA   VARCHAR2(15 CHAR) NOT NULL,
    FECHA_APERTURA DATE              DEFAULT SYSDATE NOT NULL,
    OBSERVACIONES  VARCHAR2(1000 CHAR),
    ACTIVO         NUMBER(1)         DEFAULT 1 NOT NULL,
    CONSTRAINT PK_HISTORIA_CLINICA PRIMARY KEY (ID_HISTORIA),
    CONSTRAINT UQ_HC_PACIENTE      UNIQUE (ID_PACIENTE),
    CONSTRAINT UQ_HC_NRO           UNIQUE (NRO_HISTORIA),
    CONSTRAINT FK_HC_PACIENTE      FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE) ON DELETE CASCADE,
    CONSTRAINT CK_HC_ACTIVO        CHECK (ACTIVO IN (0, 1))
);
CREATE SEQUENCE SEQ_HISTORIA_CLINICA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_HISTORIA_CLINICA_BI BEFORE INSERT ON HISTORIA_CLINICA FOR EACH ROW WHEN (NEW.ID_HISTORIA IS NULL)
BEGIN :NEW.ID_HISTORIA := SEQ_HISTORIA_CLINICA.NEXTVAL; END;
/

-- 9) CITA
CREATE TABLE CITA (
    ID_CITA         NUMBER(10)        NOT NULL,
    ID_PACIENTE     NUMBER(10)        NOT NULL,
    ID_MEDICO       NUMBER(10)        NOT NULL,
    ID_ESPECIALIDAD NUMBER(10)        NOT NULL,
    FECHA_CITA      DATE              NOT NULL,
    HORA_INICIO     VARCHAR2(5 CHAR)  NOT NULL,
    HORA_FIN        VARCHAR2(5 CHAR)  NOT NULL,
    ESTADO          VARCHAR2(20 CHAR) DEFAULT 'PROGRAMADA' NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(300 CHAR),
    CANAL_RESERVA   VARCHAR2(20 CHAR) DEFAULT 'WEB' NOT NULL,
    CODIGO_QR       VARCHAR2(100 CHAR),
    NUMERO_TURNO    NUMBER(4),
    FECHA_REGISTRO  TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CHECKIN   TIMESTAMP,
    OBSERVACIONES   VARCHAR2(500 CHAR),
    CONSTRAINT PK_CITA             PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_CITA_PACIENTE    FOREIGN KEY (ID_PACIENTE)     REFERENCES PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_CITA_MEDICO      FOREIGN KEY (ID_MEDICO)       REFERENCES MEDICO (ID_MEDICO),
    CONSTRAINT FK_CITA_ESPEC       FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD),
    CONSTRAINT CK_CITA_ESTADO      CHECK (ESTADO IN ('PROGRAMADA','CONFIRMADA','EN_ATENCION','ATENDIDA','CANCELADA','NO_ASISTIO','REPROGRAMADA')),
    CONSTRAINT CK_CITA_CANAL       CHECK (CANAL_RESERVA IN ('WEB','TELEFONO','PRESENCIAL','APP')),
    CONSTRAINT UQ_CITA_MEDICO_SLOT UNIQUE (ID_MEDICO, FECHA_CITA, HORA_INICIO)
);
CREATE SEQUENCE SEQ_CITA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_CITA_BI BEFORE INSERT ON CITA FOR EACH ROW WHEN (NEW.ID_CITA IS NULL)
BEGIN :NEW.ID_CITA := SEQ_CITA.NEXTVAL; END;
/

-- 10) DIAGNOSTICO_CIE10
CREATE TABLE DIAGNOSTICO_CIE10 (
    CODIGO      VARCHAR2(10 CHAR)  NOT NULL,
    DESCRIPCION VARCHAR2(300 CHAR) NOT NULL,
    CAPITULO    VARCHAR2(80 CHAR),
    ACTIVO      NUMBER(1)          DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CIE10        PRIMARY KEY (CODIGO),
    CONSTRAINT CK_CIE10_ACTIVO CHECK (ACTIVO IN (0, 1))
);

-- 11) ATENCION
CREATE TABLE ATENCION (
    ID_ATENCION         NUMBER(10) NOT NULL,
    ID_CITA             NUMBER(10) NOT NULL,
    ID_HISTORIA         NUMBER(10) NOT NULL,
    ID_MEDICO           NUMBER(10) NOT NULL,
    FECHA_ATENCION      TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    MOTIVO_CONSULTA     VARCHAR2(500 CHAR),
    ANAMNESIS           CLOB,
    EXAMEN_FISICO       CLOB,
    DIAGNOSTICO_CIE10   VARCHAR2(10 CHAR),
    DIAGNOSTICO_DESC    VARCHAR2(500 CHAR),
    TRATAMIENTO         CLOB,
    OBSERVACIONES       VARCHAR2(1000 CHAR),
    PRESION_ARTERIAL    VARCHAR2(15 CHAR),
    FRECUENCIA_CARDIACA NUMBER(3),
    TEMPERATURA         NUMBER(4, 1),
    PESO_KG             NUMBER(5, 2),
    TALLA_CM            NUMBER(5, 2),
    SATURACION_O2       NUMBER(3),
    FIRMADO_POR         NUMBER(10),
    FECHA_FIRMA         TIMESTAMP,
    CONSTRAINT PK_ATENCION      PRIMARY KEY (ID_ATENCION),
    CONSTRAINT UQ_ATENCION_CITA UNIQUE (ID_CITA),
    CONSTRAINT FK_ATEN_CITA     FOREIGN KEY (ID_CITA)     REFERENCES CITA (ID_CITA),
    CONSTRAINT FK_ATEN_HISTORIA FOREIGN KEY (ID_HISTORIA) REFERENCES HISTORIA_CLINICA (ID_HISTORIA),
    CONSTRAINT FK_ATEN_MEDICO   FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO (ID_MEDICO),
    CONSTRAINT FK_ATEN_CIE10    FOREIGN KEY (DIAGNOSTICO_CIE10) REFERENCES DIAGNOSTICO_CIE10 (CODIGO),
    CONSTRAINT FK_ATEN_FIRMADOR FOREIGN KEY (FIRMADO_POR) REFERENCES USUARIO (ID_USUARIO)
);
CREATE SEQUENCE SEQ_ATENCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_ATENCION_BI BEFORE INSERT ON ATENCION FOR EACH ROW WHEN (NEW.ID_ATENCION IS NULL)
BEGIN :NEW.ID_ATENCION := SEQ_ATENCION.NEXTVAL; END;
/

-- 12) RECETA
CREATE TABLE RECETA (
    ID_RECETA     NUMBER(10)        NOT NULL,
    ID_ATENCION   NUMBER(10)        NOT NULL,
    NRO_RECETA    VARCHAR2(20 CHAR) NOT NULL,
    FECHA_EMISION TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    OBSERVACIONES VARCHAR2(500 CHAR),
    CONSTRAINT PK_RECETA      PRIMARY KEY (ID_RECETA),
    CONSTRAINT UQ_RECETA_NRO  UNIQUE (NRO_RECETA),
    CONSTRAINT FK_RECETA_ATEN FOREIGN KEY (ID_ATENCION) REFERENCES ATENCION (ID_ATENCION) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_RECETA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_RECETA_BI BEFORE INSERT ON RECETA FOR EACH ROW WHEN (NEW.ID_RECETA IS NULL)
BEGIN :NEW.ID_RECETA := SEQ_RECETA.NEXTVAL; END;
/

-- 13) DETALLE_RECETA
CREATE TABLE DETALLE_RECETA (
    ID_DETALLE         NUMBER(10)         NOT NULL,
    ID_RECETA          NUMBER(10)         NOT NULL,
    NOMBRE_GENERICO    VARCHAR2(150 CHAR) NOT NULL,
    NOMBRE_COMERCIAL   VARCHAR2(150 CHAR),
    PRESENTACION       VARCHAR2(80 CHAR),
    DOSIS              VARCHAR2(80 CHAR)  NOT NULL,
    FRECUENCIA         VARCHAR2(80 CHAR)  NOT NULL,
    DURACION_DIAS      NUMBER(3)          NOT NULL,
    VIA_ADMINISTRACION VARCHAR2(30 CHAR),
    INDICACIONES       VARCHAR2(500 CHAR),
    CONSTRAINT PK_DETALLE_RECETA  PRIMARY KEY (ID_DETALLE),
    CONSTRAINT FK_DETREC_RECETA   FOREIGN KEY (ID_RECETA) REFERENCES RECETA (ID_RECETA) ON DELETE CASCADE,
    CONSTRAINT CK_DETREC_DURACION CHECK (DURACION_DIAS > 0)
);
CREATE SEQUENCE SEQ_DETALLE_RECETA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_DETALLE_RECETA_BI BEFORE INSERT ON DETALLE_RECETA FOR EACH ROW WHEN (NEW.ID_DETALLE IS NULL)
BEGIN :NEW.ID_DETALLE := SEQ_DETALLE_RECETA.NEXTVAL; END;
/

-- 14) ORDEN_EXAMEN
CREATE TABLE ORDEN_EXAMEN (
    ID_ORDEN        NUMBER(10)         NOT NULL,
    ID_ATENCION     NUMBER(10)         NOT NULL,
    TIPO_EXAMEN     VARCHAR2(30 CHAR)  NOT NULL,
    NOMBRE_EXAMEN   VARCHAR2(150 CHAR) NOT NULL,
    INDICACIONES    VARCHAR2(500 CHAR),
    ESTADO          VARCHAR2(20 CHAR)  DEFAULT 'SOLICITADO' NOT NULL,
    FECHA_SOLICITUD TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_RESULTADO TIMESTAMP,
    CONSTRAINT PK_ORDEN_EXAMEN PRIMARY KEY (ID_ORDEN),
    CONSTRAINT FK_ORDEN_ATEN   FOREIGN KEY (ID_ATENCION) REFERENCES ATENCION (ID_ATENCION) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_ORDEN_EXAMEN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_ORDEN_EXAMEN_BI BEFORE INSERT ON ORDEN_EXAMEN FOR EACH ROW WHEN (NEW.ID_ORDEN IS NULL)
BEGIN :NEW.ID_ORDEN := SEQ_ORDEN_EXAMEN.NEXTVAL; END;
/

-- 15) PAGO
CREATE TABLE PAGO (
    ID_PAGO          NUMBER(10)        NOT NULL,
    ID_CITA          NUMBER(10)        NOT NULL,
    MONTO            NUMBER(10, 2)     NOT NULL,
    METODO_PAGO      VARCHAR2(20 CHAR) NOT NULL,
    ESTADO           VARCHAR2(20 CHAR) DEFAULT 'PENDIENTE' NOT NULL,
    NRO_COMPROBANTE  VARCHAR2(30 CHAR),
    TIPO_COMPROBANTE VARCHAR2(15 CHAR),
    FECHA_PAGO       TIMESTAMP,
    FECHA_REGISTRO   TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PAGO        PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGO_CITA   FOREIGN KEY (ID_CITA) REFERENCES CITA (ID_CITA),
    CONSTRAINT CK_PAGO_MONTO  CHECK (MONTO >= 0),
    CONSTRAINT CK_PAGO_METODO CHECK (METODO_PAGO IN ('EFECTIVO','TARJETA','YAPE','PLIN','TRANSFERENCIA')),
    CONSTRAINT CK_PAGO_ESTADO CHECK (ESTADO IN ('PENDIENTE','PAGADO','ANULADO','REEMBOLSADO'))
);
CREATE SEQUENCE SEQ_PAGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_PAGO_BI BEFORE INSERT ON PAGO FOR EACH ROW WHEN (NEW.ID_PAGO IS NULL)
BEGIN :NEW.ID_PAGO := SEQ_PAGO.NEXTVAL; END;
/

-- 16) AUDITORIA_LOG
CREATE TABLE AUDITORIA_LOG (
    ID_LOG     NUMBER(10)         NOT NULL,
    ID_USUARIO NUMBER(10),
    USERNAME   VARCHAR2(50 CHAR),
    ACCION     VARCHAR2(30 CHAR)  NOT NULL,
    ENTIDAD    VARCHAR2(50 CHAR),
    ID_ENTIDAD VARCHAR2(50 CHAR),
    DETALLE    VARCHAR2(2000 CHAR),
    IP_ORIGEN  VARCHAR2(45 CHAR),
    FECHA_HORA TIMESTAMP          DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDITORIA_LOG PRIMARY KEY (ID_LOG),
    CONSTRAINT FK_AUDIT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
CREATE SEQUENCE SEQ_AUDITORIA_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_LOG_BI BEFORE INSERT ON AUDITORIA_LOG FOR EACH ROW WHEN (NEW.ID_LOG IS NULL)
BEGIN :NEW.ID_LOG := SEQ_AUDITORIA_LOG.NEXTVAL; END;
/


-- ================================================================
--  DATOS INICIALES (SEED)
-- ================================================================

-- Roles
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('ADMINISTRADOR', 'Administrador del sistema');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('GERENTE',       'Gerencia / dashboards');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('MEDICO',        'Medico especialista');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('RECEPCIONISTA', 'Personal de admision');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('PACIENTE',      'Paciente del centro medico');

-- Usuarios
-- Contrasenas: admin=Admin123 | resto=Admin123 (BCrypt)
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('admin',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36DRjk38', 'admin@trinidadtarapoto.com',     1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('gerente',   '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'gerente@trinidadtarapoto.com',   1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('recepcion', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'recepcion@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('dr.garcia', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dr.garcia@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('dra.lopez', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dra.lopez@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION)
    VALUES ('paciente1', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'paciente1@example.com',          1, 0, 0, SYSDATE);

-- Roles por usuario
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='admin'     AND r.NOMBRE='ADMINISTRADOR';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='gerente'   AND r.NOMBRE='GERENTE';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='recepcion' AND r.NOMBRE='RECEPCIONISTA';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dr.garcia' AND r.NOMBRE='MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='dra.lopez' AND r.NOMBRE='MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME='paciente1' AND r.NOMBRE='PACIENTE';

-- Especialidades
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Medicina General',      50.00, 20);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Pediatria',             70.00, 20);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Ginecologia',           80.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Cardiologia',          100.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Traumatologia',         90.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Dermatologia',          85.00, 20);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Oftalmologia',          90.00, 20);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Otorrinolaringologia',  90.00, 20);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Neurologia',           110.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Psiquiatria',          120.00, 45);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Urologia',             100.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Endocrinologia',       100.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Gastroenterologia',    100.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Reumatologia',         110.00, 30);
INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Odontologia',           60.00, 30);

-- Diagnosticos CIE-10
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('J00',   'Rinofaringitis aguda (resfriado comun)',                  'Sistema respiratorio');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('J06.9', 'Infeccion aguda de las vias respiratorias superiores',    'Sistema respiratorio');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('K29.7', 'Gastritis no especificada',                               'Sistema digestivo');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('I10',   'Hipertension esencial (primaria)',                        'Sistema circulatorio');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones',            'Endocrinas');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('M54.5', 'Lumbago no especificado',                                 'Sistema osteomuscular');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('R51',   'Cefalea',                                                 'Sintomas generales');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('R50.9', 'Fiebre, no especificada',                                 'Sintomas generales');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('Z00.0', 'Examen medico general de adulto',                         'Factores de salud');
INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('A09',   'Diarrea y gastroenteritis de presunto origen infeccioso', 'Infecciosas');

-- Medicos
INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO)
    SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '12345', 'Carlos', 'Garcia', 'Mendoza', '40123456', '942111222', 'dr.garcia@trinidadtarapoto.com', 'C-101'
    FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dr.garcia' AND e.NOMBRE='Medicina General';

INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO)
    SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '67890', 'Maria', 'Lopez', 'Vasquez', '40987654', '942333444', 'dra.lopez@trinidadtarapoto.com', 'C-205'
    FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dra.lopez' AND e.NOMBRE='Pediatria';

-- Horarios (Lun-Vie)
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 1, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 2, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 3, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 4, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 5, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 1, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 2, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 3, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 4, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 5, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';

-- Pacientes
INSERT INTO PACIENTE (ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, EMAIL, DIRECCION, DISTRITO, TIPO_SANGRE)
    SELECT u.ID_USUARIO, '70123456', 'Juan', 'Perez', 'Quispe', DATE '1990-05-15', 'M', '942555666', 'paciente1@example.com', 'Jr. Lima 123', 'Tarapoto', 'O+'
    FROM USUARIO u WHERE u.USERNAME='paciente1';

INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70234567', 'Ana',    'Rodriguez', 'Torres', DATE '1985-08-22', 'F', '942777888', 'Av. Salaverry 456',  'Tarapoto', 'A+');
INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70345678', 'Luis',   'Sanchez',    'Vega',   DATE '1978-12-03', 'M', '942999000', 'Calle Real 789',     'Morales',  'B+');
INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70456789', 'Carmen', 'Flores',     'Diaz',   DATE '1995-03-18', 'F', '942111333', 'Jr. San Martin 234', 'Tarapoto', 'AB+');

-- Historias clinicas
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-001' FROM PACIENTE WHERE DNI='70123456';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-002' FROM PACIENTE WHERE DNI='70234567';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-003' FROM PACIENTE WHERE DNI='70345678';
INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-004' FROM PACIENTE WHERE DNI='70456789';

-- Citas de ejemplo
INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE,     '09:00', '09:20', 'PROGRAMADA', 'Control general',           'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70123456' AND m.CMP='12345';
INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE,     '09:30', '09:50', 'CONFIRMADA', 'Dolor de cabeza recurrente', 'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70234567' AND m.CMP='12345';
INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE + 1, '14:00', '14:20', 'PROGRAMADA', 'Consulta pediatrica',        'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70456789' AND m.CMP='67890';
INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE + 2, '10:00', '10:20', 'PROGRAMADA', 'Chequeo anual',              'PRESENCIAL'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70345678' AND m.CMP='12345';

COMMIT;

-- Verificacion rapida
SELECT 'ROL'              AS TABLA, COUNT(*) AS FILAS FROM ROL              UNION ALL
SELECT 'USUARIO'          AS TABLA, COUNT(*) AS FILAS FROM USUARIO          UNION ALL
SELECT 'ESPECIALIDAD'     AS TABLA, COUNT(*) AS FILAS FROM ESPECIALIDAD     UNION ALL
SELECT 'MEDICO'           AS TABLA, COUNT(*) AS FILAS FROM MEDICO           UNION ALL
SELECT 'PACIENTE'         AS TABLA, COUNT(*) AS FILAS FROM PACIENTE         UNION ALL
SELECT 'CITA'             AS TABLA, COUNT(*) AS FILAS FROM CITA             UNION ALL
SELECT 'DIAGNOSTICO_CIE10' AS TABLA, COUNT(*) AS FILAS FROM DIAGNOSTICO_CIE10;
