-- ROLES
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('ADMINISTRADOR', 'Administrador del sistema');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('GERENTE',       'Gerencia / dashboards');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('MEDICO',        'Medico especialista');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('RECEPCIONISTA', 'Personal de admision');
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES ('PACIENTE',      'Paciente del centro medico');

-- USUARIOS
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('admin',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7b3XeKeUxWdeS86E36DRjk38', 'admin@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('gerente',   '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'gerente@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('recepcion', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'recepcion@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('dr.garcia', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dr.garcia@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('dra.lopez', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'dra.lopez@trinidadtarapoto.com', 1, 0, 0, SYSDATE);
INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, EMAIL, ACTIVO, BLOQUEADO, INTENTOS_FALLIDOS, FECHA_CREACION) VALUES ('paciente1', '$2a$10$qs/CZbSC9Hr9yygp9tsu6edSHrAtmB5fObyj/dj1V4ZbfvrmrN/tO', 'paciente1@example.com', 1, 0, 0, SYSDATE);

-- USUARIO_ROL
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'admin'     AND r.NOMBRE = 'ADMINISTRADOR';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'gerente'   AND r.NOMBRE = 'GERENTE';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'recepcion' AND r.NOMBRE = 'RECEPCIONISTA';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'dr.garcia' AND r.NOMBRE = 'MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'dra.lopez' AND r.NOMBRE = 'MEDICO';
INSERT INTO USUARIO_ROL (ID_USUARIO, ID_ROL) SELECT u.ID_USUARIO, r.ID_ROL FROM USUARIO u, ROL r WHERE u.USERNAME = 'paciente1' AND r.NOMBRE = 'PACIENTE';

    -- ESPECIALIDADES
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Medicina General',     50.00, 20);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Pediatria',            70.00, 20);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Ginecologia',          80.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Cardiologia',         100.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Traumatologia',        90.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Dermatologia',         85.00, 20);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Oftalmologia',         90.00, 20);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Otorrinolaringologia', 90.00, 20);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Neurologia',          110.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Psiquiatria',         120.00, 45);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Urologia',            100.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Endocrinologia',      100.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Gastroenterologia',   100.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Reumatologia',        110.00, 30);
    INSERT INTO ESPECIALIDAD (NOMBRE, PRECIO_CONSULTA, DURACION_MINUTOS) VALUES ('Odontologia',          60.00, 30);

    -- CIE-10
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('J00',   'Rinofaringitis aguda (resfriado comun)', 'Sistema respiratorio');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('J06.9', 'Infeccion aguda de las vias respiratorias superiores', 'Sistema respiratorio');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('K29.7', 'Gastritis no especificada', 'Sistema digestivo');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('I10',   'Hipertension esencial (primaria)', 'Sistema circulatorio');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones', 'Endocrinas');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('M54.5', 'Lumbago no especificado', 'Sistema osteomuscular');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('R51',   'Cefalea', 'Sintomas generales');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('R50.9', 'Fiebre, no especificada', 'Sintomas generales');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('Z00.0', 'Examen medico general de adulto', 'Factores que influyen en el estado de salud');
    INSERT INTO DIAGNOSTICO_CIE10 (CODIGO, DESCRIPCION, CAPITULO) VALUES ('A09',   'Diarrea y gastroenteritis de presunto origen infeccioso', 'Infecciosas');

    -- MEDICOS
    INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO)
    SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '12345', 'Carlos', 'Garcia', 'Mendoza', '40123456', '942111222', 'dr.garcia@trinidadtarapoto.com', 'C-101'
    FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dr.garcia' AND e.NOMBRE='Medicina General';

    INSERT INTO MEDICO (ID_USUARIO, ID_ESPECIALIDAD, CMP, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, DNI, TELEFONO, EMAIL, CONSULTORIO)
    SELECT u.ID_USUARIO, e.ID_ESPECIALIDAD, '67890', 'Maria', 'Lopez', 'Vasquez', '40987654', '942333444', 'dra.lopez@trinidadtarapoto.com', 'C-205'
    FROM USUARIO u, ESPECIALIDAD e WHERE u.USERNAME='dra.lopez' AND e.NOMBRE='Pediatria';

    -- HORARIOS
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 1, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 2, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 3, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 4, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 5, '08:00', '13:00' FROM MEDICO m WHERE m.CMP='12345';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 1, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 2, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 3, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 4, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';
    INSERT INTO HORARIO_MEDICO (ID_MEDICO, DIA_SEMANA, HORA_INICIO, HORA_FIN) SELECT m.ID_MEDICO, 5, '14:00', '18:00' FROM MEDICO m WHERE m.CMP='67890';

    -- PACIENTES
    INSERT INTO PACIENTE (ID_USUARIO, DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, EMAIL, DIRECCION, DISTRITO, TIPO_SANGRE)
    SELECT u.ID_USUARIO, '70123456', 'Juan', 'Perez', 'Quispe', DATE '1990-05-15', 'M', '942555666', 'paciente1@example.com', 'Jr. Lima 123', 'Tarapoto', 'O+'
    FROM USUARIO u WHERE u.USERNAME='paciente1';

    INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70234567', 'Ana', 'Rodriguez', 'Torres', DATE '1985-08-22', 'F', '942777888', 'Av. Salaverry 456', 'Tarapoto', 'A+');

    INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70345678', 'Luis', 'Sanchez', 'Vega', DATE '1978-12-03', 'M', '942999000', 'Calle Real 789', 'Morales', 'B+');

    INSERT INTO PACIENTE (DNI, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, SEXO, TELEFONO, DIRECCION, DISTRITO, TIPO_SANGRE)
    VALUES ('70456789', 'Carmen', 'Flores', 'Diaz', DATE '1995-03-18', 'F', '942111333', 'Jr. San Martin 234', 'Tarapoto', 'AB+');

    -- HISTORIAS CLINICAS
    INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-001' FROM PACIENTE WHERE DNI='70123456';
    INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-002' FROM PACIENTE WHERE DNI='70234567';
    INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-003' FROM PACIENTE WHERE DNI='70345678';
    INSERT INTO HISTORIA_CLINICA (ID_PACIENTE, NRO_HISTORIA) SELECT ID_PACIENTE, 'HC-2026-004' FROM PACIENTE WHERE DNI='70456789';

    -- CITAS
    INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE, '09:00', '09:20', 'PROGRAMADA', 'Control general', 'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70123456' AND m.CMP='12345';

    INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE, '09:30', '09:50', 'CONFIRMADA', 'Dolor de cabeza recurrente', 'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70234567' AND m.CMP='12345';

    INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE + 1, '14:00', '14:20', 'PROGRAMADA', 'Consulta pediatrica', 'WEB'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70456789' AND m.CMP='67890';

    INSERT INTO CITA (ID_PACIENTE, ID_MEDICO, ID_ESPECIALIDAD, FECHA_CITA, HORA_INICIO, HORA_FIN, ESTADO, MOTIVO_CONSULTA, CANAL_RESERVA)
    SELECT p.ID_PACIENTE, m.ID_MEDICO, m.ID_ESPECIALIDAD, SYSDATE + 2, '10:00', '10:20', 'PROGRAMADA', 'Chequeo anual', 'PRESENCIAL'
    FROM PACIENTE p, MEDICO m WHERE p.DNI='70345678' AND m.CMP='12345';

COMMIT;
